# Generated by Django 4.2.6 on 2023-11-26 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0001_initial"),
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myapplyjoblist",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.candidateapplication",
            ),
        ),
        migrations.AlterField(
            model_name="myapplyjoblist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
